version: '3'
services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: wedding-app
    networks:
      - wedding
      - db_postgres

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: wedding-nginx
    ports:
      - 3007:80
    networks:
      - wedding
    depends_on:
      - app

networks:
  wedding:
    driver: bridge
  db_postgres:
    external: true
  shared-network:
    external: true
